comments api
ayushsaxena2022/buzz_be pull request #3
Opened 2022-04-08 09:24 UTC by Dhruv8321

2022-04-08 10:51 UTC, vibhor-kukreja requested changes

2022-04-08 10:51 UTC, vibhor-kukreja commented on src/middleware/commentMiddleware.js
> +
Not required

2022-04-08 10:51 UTC, vibhor-kukreja commented on src/models/commentSchema.js
> +
remove

2022-04-08 10:51 UTC, vibhor-kukreja commented on src/models/commentSchema.js
> +      minlength: 2,
Min should be 5 to 10 char

2022-04-08 10:51 UTC, vibhor-kukreja commented on src/models/commentSchema.js
> +const Comment = mongoose.model('Comment', new mongoose.Schema({
Should be comments

2022-04-12 13:22 UTC, gurjot74 commented on src/routes/comments.js
> +        await post.save();
post is not defined

2022-04-12 13:44 UTC, ayushsaxena2022 commented on src/middleware/Validation.js
> +    comment: Joi.string().min(5).max(10).required()
comment can be more than 10 characters

2022-04-12 13:44 UTC, ayushsaxena2022 commented on src/models/friendlist.js
> +
remove extra lines

2022-04-12 13:44 UTC, ayushsaxena2022 commented on src/models/comment.js
> +  feed_Id: {
use one type of casing

2022-04-12 13:44 UTC, ayushsaxena2022 commented on src/routes/comments.js
> +router.post('/comments/:feed_Id', async (req, res) => {
extra lines remove

2022-04-12 13:44 UTC, ayushsaxena2022 commented on src/routes/comments.js
> +        await post.save();
no need of post.save

2022-04-13 13:48 UTC, merged